[2024-10-12T18:04:07.446-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-12T18:04:07.469-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DesafioLH.export_orders manual__2024-10-12T21:04:03.971620+00:00 [queued]>
[2024-10-12T18:04:07.483-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DesafioLH.export_orders manual__2024-10-12T21:04:03.971620+00:00 [queued]>
[2024-10-12T18:04:07.483-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-12T18:04:07.508-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): export_orders> on 2024-10-12 21:04:03.971620+00:00
[2024-10-12T18:04:07.525-0300] {standard_task_runner.py:72} INFO - Started process 80781 to run task
[2024-10-12T18:04:07.535-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'DesafioLH', 'export_orders', 'manual__2024-10-12T21:04:03.971620+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/desafiolh.py', '--cfg-path', '/tmp/tmpnvlyba98']
[2024-10-12T18:04:07.545-0300] {standard_task_runner.py:105} INFO - Job 76: Subtask export_orders
[2024-10-12T18:04:07.633-0300] {task_command.py:467} INFO - Running <TaskInstance: DesafioLH.export_orders manual__2024-10-12T21:04:03.971620+00:00 [running]> on host LAPTOP-9RLTGE5V.
[2024-10-12T18:04:07.731-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='kaue.oliveira@indicium.tech' AIRFLOW_CTX_DAG_OWNER='Kaue Oliveira' AIRFLOW_CTX_DAG_ID='DesafioLH' AIRFLOW_CTX_TASK_ID='export_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T21:04:03.971620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-12T21:04:03.971620+00:00'
[2024-10-12T18:04:07.732-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-12T18:04:07.806-0300] {python.py:240} INFO - Done. Returned value was: None
[2024-10-12T18:04:07.811-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-12T18:04:07.812-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=DesafioLH, task_id=export_orders, run_id=manual__2024-10-12T21:04:03.971620+00:00, execution_date=20241012T210403, start_date=20241012T210407, end_date=20241012T210407
[2024-10-12T18:04:07.877-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-12T18:04:07.907-0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-12T18:04:07.921-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
