[2024-10-12T18:32:07.428-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-12T18:32:07.444-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DesafioLH.export_orders manual__2024-10-12T21:32:02.216019+00:00 [queued]>
[2024-10-12T18:32:07.455-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DesafioLH.export_orders manual__2024-10-12T21:32:02.216019+00:00 [queued]>
[2024-10-12T18:32:07.456-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-12T18:32:07.483-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): export_orders> on 2024-10-12 21:32:02.216019+00:00
[2024-10-12T18:32:07.491-0300] {standard_task_runner.py:72} INFO - Started process 93468 to run task
[2024-10-12T18:32:07.495-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'DesafioLH', 'export_orders', 'manual__2024-10-12T21:32:02.216019+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/desafiolh.py', '--cfg-path', '/tmp/tmpo9sacyb7']
[2024-10-12T18:32:07.502-0300] {standard_task_runner.py:105} INFO - Job 88: Subtask export_orders
[2024-10-12T18:32:07.929-0300] {task_command.py:467} INFO - Running <TaskInstance: DesafioLH.export_orders manual__2024-10-12T21:32:02.216019+00:00 [running]> on host LAPTOP-9RLTGE5V.
[2024-10-12T18:32:08.270-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='kaue.oliveira@indicium.tech' AIRFLOW_CTX_DAG_OWNER='Kaue Oliveira' AIRFLOW_CTX_DAG_ID='DesafioLH' AIRFLOW_CTX_TASK_ID='export_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T21:32:02.216019+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-12T21:32:02.216019+00:00'
[2024-10-12T18:32:08.274-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-12T18:32:08.385-0300] {python.py:240} INFO - Done. Returned value was: None
[2024-10-12T18:32:08.393-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-12T18:32:08.394-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=DesafioLH, task_id=export_orders, run_id=manual__2024-10-12T21:32:02.216019+00:00, execution_date=20241012T213202, start_date=20241012T213207, end_date=20241012T213208
[2024-10-12T18:32:08.460-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-12T18:32:08.499-0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-12T18:32:08.513-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
